import type {HoldType,LocationId,RouteData} from '../core/contracts';
const mountain=`<svg viewBox="0 0 44 40" fill="none" aria-hidden="true"><path d="M3 33 16 8l8 15 6-10 11 20H3Z" stroke="currentColor" stroke-width="2.4" stroke-linejoin="round"/><path d="m11 18 5 4 5-4M27 20l4 3 3-2" stroke="currentColor" stroke-width="2"/></svg>`;
export type UIAction='gym'|'outdoor'|'home'|'edit'|'test'|'save'|'new'|'undo'|'delete'|'rotate'|'climb'|'role'|'clip'|'fall'|'reset'|'lower'|'feed'|'take'|'lock'|'neutral'|'export'|'import'|'help'|'pause'|'audio'|'look'|'wallColor';
export class UI {
  root:HTMLDivElement; private toastTimer=0;
  onAction:(action:UIAction)=>void=()=>{};
  onHold:(type:HoldType)=>void=()=>{}; onColor:(color:string)=>void=()=>{};
  onName:(name:string)=>void=()=>{};onMark:(kind:'start'|'finish',value:boolean)=>void=()=>{};
  onScale:(value:number)=>void=()=>{};onLoad:(id:string)=>void=()=>{};
  constructor(parent:HTMLElement){
    this.root=document.createElement('div');this.root.id='interface';parent.append(this.root);
    this.root.innerHTML=`
    <header class="topbar"><button class="brand" data-action="home" aria-label="Home">${mountain}<span>CLIMB<span>WITH FRIENDS</span></span></button><div class="location-tabs" hidden><button data-action="gym" class="active">The Hearth <span>GYM</span></button><button data-action="outdoor">Juniper Ridge <span>OUTDOORS</span></button></div><div class="top-right"><span class="local-badge"><i></i> LOCAL DUO</span><button class="icon-btn" data-action="audio" aria-label="Toggle sound">♪</button><button class="icon-btn" data-action="help" aria-label="Controls">?</button></div></header>
    <section class="welcome"><div class="eyebrow"><span></span> A SMALL PLACE FOR BIG ADVENTURES</div><h1>A little higher,<br><em>together.</em></h1><p>Make a route. Find your rhythm.<br>Leave a little chalk with good company.</p><div class="menu-cards"><button class="destination selected" data-action="gym"><span class="destination-icon">⌂</span><span><small>BUILD · CLIMB · HANG OUT</small><strong>The Hearth</strong><span>Your neighborhood climbing gym</span></span><b>↗</b></button><button class="destination" data-action="outdoor"><span class="destination-icon mountain">△</span><span><small>CLIMB · BELAY · EXPLORE</small><strong>Juniper Ridge</strong><span>A quiet route above the valley</span></span><b>↗</b></button></div><div class="menu-note"><span class="tiny-stars">✳</span> A cozy climbing prototype. Best shared.</div></section>
    <div class="menu-scene-label"><span>01 / THE HEARTH</span><strong>One more try before coffee.</strong><small>WARM LIGHT. GOOD COMPANY. NEW POSSIBILITIES.</small></div>
    <section class="route-card" hidden><div class="eyebrow" id="location-label">THE HEARTH / YOUR GYM</div><h2 id="route-title">First light</h2><div class="route-meta"><i id="route-dot"></i><span id="route-grade">A friendly first route</span><span class="separator">·</span><span id="hold-count">18 holds</span></div><p id="objective">Walk over to the wall. There’s room for your next idea.</p></section>
    <section class="editor-panel" hidden><div class="panel-heading"><span class="eyebrow">ROUTE WORKSHOP</span><button data-action="edit" class="close" aria-label="Close route editor">×</button></div><h2>A route of your own.</h2><label class="field-label" for="route-name">ROUTE NAME</label><input id="route-name" maxlength="60" value="First light"/><div class="field-row"><label class="field-label" for="route-color">ROUTE COLOR</label><input id="route-color" type="color" value="#dd795f"/></div><div class="swatches"><button style="--swatch:#dd795f" data-color="#dd795f" aria-label="Clay"></button><button style="--swatch:#d7ad57" data-color="#d7ad57" aria-label="Ochre"></button><button style="--swatch:#7dada5" data-color="#7dada5" aria-label="Sage"></button><button style="--swatch:#8495c1" data-color="#8495c1" aria-label="Blue"></button><button style="--swatch:#b992b0" data-color="#b992b0" aria-label="Heather"></button></div><span class="field-label">PICK A HOLD</span><div class="hold-palette">${(['jug','crimp','sloper','pinch','foothold'] as HoldType[]).map((t,i)=>`<button data-hold="${t}" class="${i===0?'active':''}"><span class="hold-shape ${t}"></span>${t}</button>`).join('')}</div><div class="selection-box"><span id="selection-label">Click the wall to place a hold</span><div class="selection-tools"><button data-action="rotate" title="Rotate selected hold (R)">↻ Rotate</button><button data-action="delete" title="Delete selected hold">× Delete</button></div><div class="marker-row"><label><input type="checkbox" id="start-hold"/> Start</label><label><input type="checkbox" id="finish-hold"/> Finish</label></div><label class="scale-row">Size<input id="hold-scale" type="range" min="0.65" max="1.5" step="0.05" value="1"/></label></div><div class="editor-primary"><button data-action="save" class="primary">Save route <span>↓</span></button><button data-action="test" class="outline">Test climb <span>↗</span></button></div><div class="editor-secondary"><button data-action="new">New</button><button data-action="undo">Undo</button><button data-action="export">Export</button><button data-action="import">Import</button></div><label class="field-label" for="saved-routes">YOUR ROUTE SHELF</label><select id="saved-routes"><option value="">Load a saved route…</option></select><p class="editor-hint">Click to place · Drag to move<br>R to rotate · Delete to remove · ⌘Z undo</p></section>
    <section class="session-panel" hidden><div class="eyebrow" id="role-label">YOU / CLIMBER</div><div class="session-status"><i></i><span id="state-label">Finding your feet</span></div><div id="outdoor-actions" hidden><button data-action="role">Switch role <kbd>Tab</kbd></button><div class="belay-actions" hidden><button data-action="feed">Feed <kbd>F</kbd></button><button data-action="take">Take <kbd>G</kbd></button><button data-action="lock">Brake <kbd>Space</kbd></button><button data-action="lower">Lower <kbd>L</kbd></button></div><div class="rope-status"><span id="rope-label">Rope ready</span><div><span id="rope-meter"></span></div></div></div><button id="edit-button" data-action="edit">Set a route <kbd>R</kbd></button><button id="wall-color-button" data-action="wallColor">Wall mood <span>◐</span></button><button data-action="reset" class="quiet">Back to the ground <span>↺</span></button></section>
    <footer class="play-footer" hidden><div class="context-action"><span id="context-icon">↟</span><div><strong id="context-title">Find your next move</strong><small id="context-subtitle">WASD to wander · Hold right mouse to look</small></div><button id="context-button" data-action="climb">Start climbing <kbd>E</kbd></button></div><div class="footer-line"><span>TAKE YOUR TIME. THE TOP CAN WAIT.</span><div><span>WASD <b>MOVE</b></span><span>RMB <b>LOOK</b></span><span>ESC <b>PAUSE</b></span></div></div></footer>
    <div class="toast" role="status" hidden></div><div class="loading">Finding a little sunlight<span></span></div>
    <dialog id="help-dialog"><button class="dialog-close" aria-label="Close">×</button><div class="eyebrow">A LITTLE FIELD GUIDE</div><h2>Find your rhythm.</h2><p>One local session, two climbing partners. Switch roles whenever you like.</p><div class="help-grid"><div><h3>Wander</h3><p><kbd>W A S D</kbd> Walk<br><kbd>Shift</kbd> Jog<br><kbd>Right drag</kbd> Look around<br><kbd>Wheel</kbd> Camera distance</p></div><div><h3>Climb</h3><p><kbd>E</kbd> Start / leave wall<br><kbd>W / Space</kbd> Next hold<br><kbd>A S D</kbd> Choose direction<br><kbd>C</kbd> Clip quickdraw<br><kbd>X</kbd> Test a fall outdoors</p></div><div><h3>Build</h3><p><kbd>R</kbd> Open workshop / rotate<br><kbd>Click</kbd> Place or select<br><kbd>Drag</kbd> Move hold<br><kbd>Delete</kbd> Remove<br><kbd>⌘ / Ctrl Z</kbd> Undo</p></div><div><h3>Belay</h3><p><kbd>Tab</kbd> Switch roles<br><kbd>F / G</kbd> Feed / take slack<br><kbd>Space</kbd> Brake / catch<br><kbd>L</kbd> Lower partner<br>Partner climbs and clips while you belay.</p></div></div><p class="fineprint">A playful approximation of climbing, designed for a game. Saved routes stay in this browser; export JSON to keep or share them.</p><button class="primary dialog-close-bottom">Let’s climb ↗</button></dialog>
    <dialog id="pause-dialog"><div class="eyebrow">A MOMENT TO BREATHE</div><h2>No rush.</h2><p>The mountain will still be here.</p><button class="primary" data-action="pause">Keep climbing ↗</button><button class="outline" data-action="home">Back to the hearth menu</button></dialog>
    <input id="route-file" type="file" accept="application/json,.json" hidden/>`;
    this.root.addEventListener('click',e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-action],[data-hold],[data-color]');if(!target)return;if(target.dataset.action)this.onAction(target.dataset.action as UIAction);if(target.dataset.hold)this.onHold(target.dataset.hold as HoldType);if(target.dataset.color)this.onColor(target.dataset.color);});
    this.el<HTMLInputElement>('route-name').addEventListener('input',e=>this.onName((e.target as HTMLInputElement).value));
    this.el<HTMLInputElement>('route-color').addEventListener('input',e=>this.onColor((e.target as HTMLInputElement).value));
    for(const kind of ['start','finish'] as const)this.el<HTMLInputElement>(`${kind}-hold`).addEventListener('change',e=>this.onMark(kind,(e.target as HTMLInputElement).checked));
    this.el<HTMLInputElement>('hold-scale').addEventListener('input',e=>this.onScale(Number((e.target as HTMLInputElement).value)));
    this.el<HTMLSelectElement>('saved-routes').addEventListener('change',e=>{const id=(e.target as HTMLSelectElement).value;if(id)this.onLoad(id);});
    this.root.querySelectorAll('.dialog-close,.dialog-close-bottom').forEach(b=>b.addEventListener('click',()=>this.el<HTMLDialogElement>('help-dialog').close()));
  }
  el<T extends HTMLElement=HTMLElement>(id:string){return this.root.querySelector<T>(`#${id}`)!;}
  show(selector:string,visible:boolean){const e=this.root.querySelector<HTMLElement>(selector);if(e)e.hidden=!visible;}
  mode(menu:boolean,editor:boolean,outdoor:boolean){
    this.root.classList.toggle('menu-mode',menu);this.root.classList.toggle('editing',editor);
    this.show('.welcome',menu);this.show('.menu-scene-label',menu);this.show('.location-tabs',!menu);this.show('.route-card',!menu&&!editor);this.show('.editor-panel',editor);this.show('.session-panel',!menu&&!editor);this.show('.play-footer',!menu);this.show('#outdoor-actions',outdoor);this.show('#edit-button',!outdoor);this.show('#wall-color-button',!outdoor);
    this.root.querySelectorAll('.location-tabs button').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.action===(outdoor?'outdoor':'gym')));
  }
  route(route:RouteData,location:LocationId){this.el('route-title').textContent=route.name;this.el('route-dot').style.background=route.color;this.el('route-grade').textContent=route.grade;this.el('hold-count').textContent=`${route.holds.length} holds`;this.el('location-label').textContent=location==='gym'?'THE HEARTH / YOUR GYM':'JUNIPER RIDGE / ALPINE GRANITE';}
  editor(route:RouteData,selected:ReturnType<import('../routes/RouteEditor').RouteEditor['getSelected']>,type:HoldType){
    if(document.activeElement!==this.el('route-name'))this.el<HTMLInputElement>('route-name').value=route.name;
    this.el<HTMLInputElement>('route-color').value=selected?.color??route.color;
    this.el('selection-label').textContent=selected?`${selected.type[0].toUpperCase()+selected.type.slice(1)} selected`:'Click the wall to place a hold';
    this.el<HTMLInputElement>('start-hold').checked=selected?.start??false;this.el<HTMLInputElement>('finish-hold').checked=selected?.finish??false;this.el<HTMLInputElement>('hold-scale').value=String(selected?.scale??1);
    this.root.querySelectorAll<HTMLElement>('[data-hold]').forEach(b=>b.classList.toggle('active',b.dataset.hold===type));
  }
  library(routes:RouteData[]){const select=this.el<HTMLSelectElement>('saved-routes');select.replaceChildren(new Option('Load a saved route…',''));for(const route of routes)select.add(new Option(route.name,route.id));}
  toast(message:string){const e=this.root.querySelector<HTMLElement>('.toast')!;e.textContent=message;e.hidden=false;clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>e.hidden=true,3600);}
  context(title:string,subtitle:string,button:string,action:UIAction='climb'){this.el('context-title').textContent=title;this.el('context-subtitle').textContent=subtitle;const b=this.el('context-button');b.textContent=button;b.dataset.action=action;}
  help(){this.el<HTMLDialogElement>('help-dialog').showModal();}
  loading(show:boolean){this.show('.loading',show);}
}
